
version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"


sphinx:
  configuration: docs/source/conf.py


python:
  install:
    - method: pip
      path: .
      requirements: docs/requirements.txt
      extra_requirements:
        - doc
python:
  version: "3.8"
  install:
    - requirements: docs/requirements.txt